services:
  assets:
    build: assets

  core-deps:
    build:
      context: core
      target: deps

  core:
    build: core
    depends_on:
      - assets
      - core-deps

  sandbox-deps:
    build:
      context: sandbox
      target: deps

  sandbox:
    build: sandbox
    ports:
      - "127.0.0.1:2437:5173"
    depends_on:
      - sandbox-deps
      - core