services:
  assets:
    build: assets

  core:
    build: core

  interface-deps:
    build:
      context: interface
      target: deps

  interface:
    build:
      context: interface
      additional_contexts:
        autochess-assets: service:assets
        autochess-core: service:core

  sandbox-deps:
    build:
      context: sandbox
      target: deps

  sandbox:
    build:
      context: sandbox
      additional_contexts:
        autochess-core: service:core
        autochess-interface: service:interface
    ports:
      - "127.0.0.1:2437:2437"
    develop:
      watch:
        - action: sync
          path: sandbox
          target: /autochess/sandbox
        - action: sync
          path: interface
          target: /autochess/interface
        - action: sync
          path: core
          target: /autochess/core

  offline-deps:
    build:
      context: offline
      target: deps

  offline:
    build:
      context: offline
      additional_contexts:
        autochess-core: service:core
        autochess-interface: service:interface
    ports:
      - "127.0.0.1:28020:28020"
    develop:
      watch:
        - action: sync
          path: offline
          target: /autochess/offline
        - action: sync
          path: interface
          target: /autochess/interface
        - action: sync
          path: core
          target: /autochess/core

  offline-publish:
    build:
      context: .
      dockerfile: offline/publish.Dockerfile
      additional_contexts:
        autochess-offline: service:offline
    stdin_open: true
    tty: true

  coverage:
    build:
      context: .
      dockerfile: coverage/Dockerfile
      additional_contexts:
        autochess-core: service:core
    ports:
      - "127.0.0.1:6245:80"

  back-deps:
    build:
      context: back
      target: deps

  back:
    build:
      context: back
      additional_contexts:
        autochess-core: service:core
        autochess-database: service:database
    environment:
      DATABASE_HOST: database
      DATABASE_USERNAME: user
      DATABASE_DB_NAME: autochess
      VITE_WEBSOCKET_PROTOCOL: ${VITE_WEBSOCKET_PROTOCOL}
      REDIS_URL: redis://bus
    ports:
      - 127.0.0.1:${VITE_WEBSOCKET_PORT_A}:3000
    depends_on:
      - database
      - replication
      - bus
      - prometheus
      - loki
    restart: on-failure:3
    develop:
      watch:
        - action: rebuild
          path: back
        - action: rebuild
          path: core

  back-b:
    extends: back
    ports: !override
      - 127.0.0.1:${VITE_WEBSOCKET_PORT_B}:3000

  back-c:
    extends: back
    ports: !override
      - 127.0.0.1:${VITE_WEBSOCKET_PORT_C}:3000

  back-d:
    extends: back
    ports: !override
      - 127.0.0.1:${VITE_WEBSOCKET_PORT_D}:3000

  back-e:
    extends: back
    ports: !override
      - 127.0.0.1:${VITE_WEBSOCKET_PORT_E}:3000

  database:
    build: database
    restart: on-failure:3

  replication:
    build:
      context: replication
      additional_contexts:
        autochess-database: service:database
    depends_on:
      - database
    restart: on-failure:3

  bus:
    image: redis:7
    restart: on-failure:3

  ingame-deps:
    build:
      context: ingame
      target: deps

  ingame:
    build:
      context: ingame
      args:
        - VITE_WEBSOCKET_PROTOCOL=${VITE_WEBSOCKET_PROTOCOL}
        - VITE_WEBSOCKET_PORTS=${VITE_WEBSOCKET_PORTS}
        - VITE_WEBSOCKET_DOMAINS=${VITE_WEBSOCKET_DOMAINS}
      additional_contexts:
        autochess-interface: service:interface
    environment:
      VITE_WEBSOCKET_PROTOCOL: ${VITE_WEBSOCKET_PROTOCOL}
      VITE_WEBSOCKET_PORTS: ${VITE_WEBSOCKET_PORTS}
      VITE_WEBSOCKET_DOMAINS: ${VITE_WEBSOCKET_DOMAINS}
    ports:
      - 127.0.0.1:53015:53015
    depends_on:
      - back
    develop:
      watch:
        - action: sync
          path: ingame
          target: /autochess/ingame
        - action: sync
          path: interface
          target: /autochess/interface
        - action: sync
          path: core
          target: /autochess/core

  prometheus:
    build: prometheus
    ports:
      - 127.0.0.1:32090:9090
    restart: on-failure:3

  loki:
    image: grafana/loki
    ports:
      - 127.0.0.1:31090:3100
    restart: on-failure:3

  blog:
    build: blog