services:
  assets:
    build: assets

  core:
    build: core

  interface-deps:
    build:
      context: interface
      target: deps

  interface:
    build: interface
    depends_on:
      - assets
      - core
      - interface-deps

  sandbox-deps:
    build:
      context: sandbox
      target: deps

  sandbox:
    build: sandbox
    ports:
      - "127.0.0.1:2437:5173"
    depends_on:
      - sandbox-deps
      - core
      - interface

  offline-deps:
    build:
      context: offline
      target: deps

  offline:
    build: offline
    ports:
      - "127.0.0.1:5423:5173"
    depends_on:
      - offline-deps
      - core
      - interface

  coverage:
    build:
      context: .
      dockerfile: coverage/Dockerfile
    ports:
      - "6245:80"
    depends_on:
      - core

  mongo-config-server-node0:
    build: mongo-config-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      REPLICASET: configsvrRs
      NODE_0: mongo-config-server-node0
      NODE_1: mongo-config-server-node1
      NODE_2: mongo-config-server-node2
      IS_REPLICA_SET_INITIATOR: true
    volumes:
      - mongo-config-server-node0-data:/data/db
      - mongo-config-server-node0-config:/data/configdb

  mongo-config-server-node1:
    build: mongo-config-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      REPLICASET: configsvrRs
      NODE_0: mongo-config-server-node0
      NODE_1: mongo-config-server-node1
      NODE_2: mongo-config-server-node2
    volumes:
      - mongo-config-server-node1-data:/data/db
      - mongo-config-server-node1-config:/data/configdb

  mongo-config-server-node2:
    build: mongo-config-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      REPLICASET: configsvrRs
      NODE_0: mongo-config-server-node0
      NODE_1: mongo-config-server-node1
      NODE_2: mongo-config-server-node2
    volumes:
      - mongo-config-server-node2-data:/data/db
      - mongo-config-server-node2-config:/data/configdb

  mongo-shard0-node0:
    build: mongo-shard
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      REPLICASET: shard0rs
      NODE_0: mongo-shard0-node0
      NODE_1: mongo-shard0-node1
      IS_REPLICA_SET_INITIATOR: true
    volumes:
      - mongo-shard0-node0-data:/data/db
      - mongo-shard0-node0-config:/data/configdb

  mongo-shard0-node1:
    build: mongo-shard
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      REPLICASET: shard0rs
      NODE_0: mongo-shard0-node0
      NODE_1: mongo-shard0-node1
    volumes:
      - mongo-shard0-node1-data:/data/db
      - mongo-shard0-node1-config:/data/configdb

  mongo-shard1-node0:
    build: mongo-shard
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      REPLICASET: shard1rs
      NODE_0: mongo-shard1-node0
      NODE_1: mongo-shard1-node1
      IS_REPLICA_SET_INITIATOR: true
    volumes:
      - mongo-shard1-node0-data:/data/db
      - mongo-shard1-node0-config:/data/configdb

  mongo-shard1-node1:
    build: mongo-shard
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      REPLICASET: shard1rs
      NODE_0: mongo-shard1-node0
      NODE_1: mongo-shard1-node1
    volumes:
      - mongo-shard1-node1-data:/data/db
      - mongo-shard1-node1-config:/data/configdb

  mongo-router-node0:
    build: mongo-router
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      DB_USERNAME: user
      DB_PASSWORD: example
      MONGO_INITDB_DATABASE: autochess
      NODE_0: mongo-router-node0
      NODE_1: mongo-router-node1
      SHARD_REPLICA_SET_0: shard0rs
      SHARD_REPLICA_SET_1: shard1rs
      SHARD_0_NODE_0: mongo-shard0-node0
      SHARD_0_NODE_1: mongo-shard0-node1
      SHARD_1_NODE_0: mongo-shard1-node0
      SHARD_1_NODE_1: mongo-shard1-node1
      IS_SHARDING_INITIATOR: true
      CONFIG_SERVER_REPLICA_SET: configsvrRs
      CONFIG_SERVER_NODE_0: mongo-config-server-node0
      CONFIG_SERVER_NODE_1: mongo-config-server-node1
      CONFIG_SERVER_NODE_2: mongo-config-server-node2
    depends_on:
      - mongo-config-server-node0
      - mongo-config-server-node1
      - mongo-config-server-node2
      - mongo-shard0-node0
      - mongo-shard0-node1
      - mongo-shard1-node0
      - mongo-shard1-node1
    volumes:
      - mongo-router-node0-data:/data/db
      - mongo-router-node0-config:/data/configdb
    ports:
      - "27017:27017"

  mongo-router-node1:
    build: mongo-router
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      DB_USERNAME: user
      DB_PASSWORD: example
      MONGO_INITDB_DATABASE: autochess
      NODE_0: mongo-router-node0
      NODE_1: mongo-router-node1
      SHARD_REPLICA_SET_0: shard0rs
      SHARD_REPLICA_SET_1: shard1rs
      SHARD_0_NODE_0: mongo-shard0-node0
      SHARD_0_NODE_1: mongo-shard0-node1
      SHARD_1_NODE_0: mongo-shard1-node0
      SHARD_1_NODE_1: mongo-shard1-node1
      CONFIG_SERVER_REPLICA_SET: configsvrRs
      CONFIG_SERVER_NODE_0: mongo-config-server-node0
      CONFIG_SERVER_NODE_1: mongo-config-server-node1
      CONFIG_SERVER_NODE_2: mongo-config-server-node2
    depends_on:
      - mongo-config-server-node0
      - mongo-config-server-node1
      - mongo-config-server-node2
      - mongo-shard0-node0
      - mongo-shard0-node1
      - mongo-shard1-node0
      - mongo-shard1-node1
    volumes:
      - mongo-router-node1-data:/data/db
      - mongo-router-node1-config:/data/configdb
    ports:
      - "27018:27017"

  back:
    build: back
    environment:
      MONGODB_USERNAME: user
      MONGODB_PASSWORD: example
      MONGODB_DATABASE: autochess
      VITE_WEBSOCKET_PROTOCOL: ${VITE_WEBSOCKET_PROTOCOL}
    ports:
      - ${VITE_WEBSOCKET_PORT}:3000
    depends_on:
      - core
      - mongo-router-node0
      - mongo-router-node1

  ingame:
    build:
      context: ingame
      args:
        - VITE_WEBSOCKET_PROTOCOL=${VITE_WEBSOCKET_PROTOCOL}
        - VITE_WEBSOCKET_PORT=${VITE_WEBSOCKET_PORT}
        - VITE_BACK_DOMAIN=${VITE_BACK_DOMAIN}
    environment:
      VITE_WEBSOCKET_PROTOCOL: ${VITE_WEBSOCKET_PROTOCOL}
      VITE_WEBSOCKET_PORT: ${VITE_WEBSOCKET_PORT}
      VITE_BACK_DOMAIN: ${VITE_BACK_DOMAIN}
    ports:
      - 53015:53015
    depends_on:
      - back
      - core
      - interface

volumes:
  mongo-config-server-node0-data:
  mongo-config-server-node0-config:
  mongo-config-server-node1-data:
  mongo-config-server-node1-config:
  mongo-config-server-node2-data:
  mongo-config-server-node2-config:
  mongo-shard0-node0-data:
  mongo-shard0-node0-config:
  mongo-shard0-node1-data:
  mongo-shard0-node1-config:
  mongo-shard1-node0-data:
  mongo-shard1-node0-config:
  mongo-shard1-node1-data:
  mongo-shard1-node1-config:
  mongo-router-node0-data:
  mongo-router-node0-config:
  mongo-router-node1-data:
  mongo-router-node1-config: