services:
  assets:
    build: assets

  core:
    build: core

  interface-deps:
    build:
      context: interface
      target: deps

  interface:
    build: interface
    depends_on:
      - assets
      - core
      - interface-deps

  sandbox-deps:
    build:
      context: sandbox
      target: deps

  sandbox:
    build: sandbox
    ports:
      - "127.0.0.1:2437:5173"
    depends_on:
      - sandbox-deps
      - core
      - interface