services:
  assets:
    build: assets

  core:
    build: core

  interface-deps:
    build:
      context: interface
      target: deps

  interface:
    build: interface
    depends_on:
      - assets
      - core
      - interface-deps

  sandbox-deps:
    build:
      context: sandbox
      target: deps

  sandbox:
    build: sandbox
    ports:
      - "127.0.0.1:2437:5173"
    depends_on:
      - sandbox-deps
      - core
      - interface

  offline-deps:
    build:
      context: offline
      target: deps

  offline:
    build: offline
    ports:
      - "127.0.0.1:5423:5173"
    depends_on:
      - offline-deps
      - core
      - interface

  coverage:
    build:
      context: .
      dockerfile: coverage/Dockerfile
    ports:
      - "6245:80"
    depends_on:
      - core


  back:
    build: back
    environment:
      DATABASE_HOST: database
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: example
      DATABASE_DB_NAME: autochess
      VITE_WEBSOCKET_PROTOCOL: ${VITE_WEBSOCKET_PROTOCOL}
      REDIS_URL: redis://bus
    ports:
      - ${VITE_WEBSOCKET_PORT_A}:3000
    depends_on:
      - core
      - database
      - database-secondary
      - bus
    restart: always

  back-b:
    extends: back
    ports: !override []

  back-c:
    extends: back
    ports: !override []

  back-d:
    extends: back
    ports: !override []

  back-e:
    extends: back
    ports: !override []

  database:
    build: database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: autochess

  database-secondary:
    build: database-secondary
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      POSTGRES_DB: autochess
    depends_on:
      - database

  bus:
    image: redis

  ingame:
    build:
      context: ingame
      args:
        - VITE_WEBSOCKET_PROTOCOL=${VITE_WEBSOCKET_PROTOCOL}
        - VITE_WEBSOCKET_PORTS=${VITE_WEBSOCKET_PORT_A}
        - VITE_WEBSOCKET_DOMAINS=${VITE_WEBSOCKET_DOMAINS}
    environment:
      VITE_WEBSOCKET_PROTOCOL: ${VITE_WEBSOCKET_PROTOCOL}
      VITE_WEBSOCKET_PORTS: ${VITE_WEBSOCKET_PORT_A}
      VITE_WEBSOCKET_DOMAINS: ${VITE_WEBSOCKET_DOMAINS}
    ports:
      - 53015:53015
    depends_on:
      - back
      - core
      - interface
