services:
  core:
    extends:
      file: compose.yml
      service: core

  database:
    extends:
      file: compose.yml
      service: database

  back:
    extends:
      file: compose.yml
      service: back
    ports: !override
      - ${VITE_WEBSOCKET_PORT_A}:3000

  back-b:
    extends:
      file: compose.yml
      service: back
    ports: !override
      - ${VITE_WEBSOCKET_PORT_B}:3000

  back-c:
    extends:
      file: compose.yml
      service: back
    ports: !override
      - ${VITE_WEBSOCKET_PORT_C}:3000

  assets:
    extends:
      file: compose.yml
      service: assets

  interface-deps:
    extends:
      file: compose.yml
      service: interface-deps

  interface:
    extends:
      file: compose.yml
      service: interface

  ingame:
    extends:
      file: compose.yml
      service: ingame
    environment:
      VITE_WEBSOCKET_PORTS: 28035,28036,28037
      VITE_WEBSOCKET_DOMAINS: ${VITE_WEBSOCKET_DOMAINS}
    depends_on:
      - back
      - back-b
      - back-c