export enum Appellation {
	Soldier = "Soldier",
	Knight = "Knight",
	KnightTemplar = "Knight Templar",
	//Swordsman = "Swordsman",
	//ArmoredAxeman = "Armored Axeman",
	Orc = "Orc",
	//ArmoredOrc = "Armored Orc",
	EliteOrc = "Elite Orc",
	//Skeleton = "Skeleton",
	//ArmoredSkeleton = "Armored Skeleton",
	Slime = "Slime",
	Lancer = "Lancer",
	Wizard = "Wizard",
	Priest = "Priest",
	//Archer = "Archer",
	//Werewolf = "Werewolf",
	Werebear = "Werebear",
	OrcRider = "Orc Rider",
	GreatswordSkeleton = "Greatsword Skeleton",
	//SkeletonArcher = "Skeleton Archer",
}
